name: Merge to main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ./src/AzureTableStorageSeeder.Console
    - name: Build
      run: dotnet build ./src/AzureTableStorageSeeder.Console --configuration Release --no-restore /p:ContinuousIntegrationBuild=true